export const SET_MAIN_PAGE_STATE = 'SET_MAIN_PAGE_STATE';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const RESET_FILTER_OPTIONS = 'RESET_FILTER_OPTIONS';
export const SET_ISSUE_STATE_FILTER_OPTION = 'SET_ISSUE_STATE_FILTER_OPTION';
export const SET_WRITTEN_BY_ME_FILTER_OPTION = 'SET_WRITTEN_BY_ME_FILTER_OPTION';
export const SET_ASSIGNED_TO_ME_FILTER_OPTION = 'SET_ASSIGNED_TO_ME_FILTER_OPTION';
export const SET_COMMENTED_BY_ME_FILTER_OPTION = 'SET_COMMENTED_BY_ME_FILTER_OPTION';
export const SET_ASSIGNEES_FILTER_OPTION = 'SET_ASSIGNEES_FILTER_OPTION';
export const SET_LABELS_FILTER_OPTION = 'SET_LABELS_FILTER_OPTION';
export const SET_MILESTONE_NAME_FILTER_OPTION = 'SET_MILESTONE_NAME_FILTER_OPTION';
export const SET_AUTHOR_FILTER_OPTION = 'SET_AUTHOR_FILTER_OPTION';
export const SET_PAGE_FILTER_OPTION = 'SET_PAGE_FILTER_OPTION';
